### ISSUE TITLE
Problem with passing Icon component to RsuiteUI.Nav.Item component

### ISSUE THREAD

**Issue by ghost** [shurygindv/bs-rsuite-ui-react#1]
I tried multiple things but still can't make this component work as I would like. I'm beginner with ReasonML, so this is maybe the biggest issue here 😄.

Problem / Question:
- How pass `Icon` component to this component?
- How pass `onClick` / `onSelect` handler.

Tried something like this but still no success:
`<RsuiteUi.Nav.Item onSelect={_ => Route.go(Home)} icon={() => <RsuiteUi.Icon icon="dashboard" />}>`

**Comment by shurygindv** [comment]
Dear, @karolfalkiewicz , I appreciate your time, really, sorry for the delay with the response! Thank you so much for your issue! 

Please, pull! Incorrect propType of `icon` was fixed in `master` branch of github repo (not in npm indexes yet)

**Example:**
```reason
  let selectItem = (value, e) => {
    Js.log(value)
  };

  let handleClick = (e) => {
    Js.log(e)
  };


  RsuiteUi.(
    <Nav onSelect={selectItem} >
       <Nav.Item  icon={<Icon icon="dashboard" />} onClick={handleClick} >
          {React.string("Child")}
       </Nav.Item>

      <Nav.Item icon={<Icon icon="dashboard" />} onClick={handleClick} >
         {React.string("Child2")}
      </Nav.Item>
  </Nav> 
```
p.s please, let me know about any problem with repo, I will try it to make better! Thank you.

**Comment by ghost** [comment]
@shurygindv 
Ok thx for your response. I thought that there is error in my code mostly. Didn't expect that 😄. Will check this asap.

PS: Creating new package number and updating npm version shoudn't be a problem 😆 
PS2: Passing component to `icon` prop shouldn't be done by using function? Would be similar to normal ReasonReact behavior. Maybe type for this prop should be `unit => React.element=?` or something similar.

**Comment by shurygindv** [comment]
@karolfalkiewicz, 

1. yep, sure, a package has just updated on npm registry, now the version is 1.0.2 instead 1.0.0
2. .re bindings according to official rsuite docs (not repo yet, in progress..) and it looks like:

[snippet](https://github.com/rsuite/rsuite/blob/master/src/Nav/NavItem.d.ts#L19)
```js
  /** Sets the icon for the component */
  icon?: React.ReactElement<IconProps>;
```
Notably, not React.FC either React.Component and etc, exact React.ReactElement (TS) == React.element (in ReasonML)

p.s thank you for your feedback, it's a good point to think about improving DX

**Comment by ghost** [comment]
@shurygindv Hmm but doing it 1:1 to what ts binding say won't be wrong according to https://reasonml.github.io/reason-react/docs/en/component-as-prop ?
