### ISSUE TITLE
On select pagination

### ISSUE THREAD

**Issue by virgiledelplace** [shurygindv/bs-rsuite-ui-react#13]
Hello,

thanks for this bindings, here no onSelect method for pagination components ? i try with buttonComponentClass for bind my onclick button but dont know how to build my pagination with that.

Thanks you in advance

**Comment by shurygindv** [comment]
@virgiledelplace, fixed, could you re-check the last changes? Thank you!

**Comment by virgiledelplace** [comment]
I do this on my local lib, im ok with that changes, thanks you!
