### ISSUE TITLE
Using bs-css to style Rsuite components (conflict with inline styles)

### ISSUE THREAD

**Issue by ghost** [shurygindv/bs-rsuite-ui-react#2]
Hi
I tried using https://github.com/SentiaAnalytics/bs-css to style my components, but no luck. I have something like this:
```
module Styles = {
  open Css;
  let container = style([height(pct(100.))]);
  let sidebar =
    style([
      width(px(56)),
      display(`flex),
      flex3(~grow=0., ~shrink=0., ~basis=px(56)),
    ]);
};
...
<RsuiteUi.Container className=Styles.container>
    <RsuiteUi.Sidebar className=Styles.sidebar>
```
Both classes were added to components, but `RsuiteUI.Sidebar` generates some inline styles with override my css. Is there any way to block this behavior?

**Comment by shurygindv** [comment]
Hello! I'm glad to see your post again, no, really, it stirs up interest to investigate new ways and improve code repo. Thank you!

Unfortunately, I can't control inline styles of `Sidebar` component, you may refer to `official rsuite repo` by your question, maybe they are generous and will add `prop` preventing styles in specific cases... But! You can solve your problem as next (yep, I agree with you that in not good):

```
let sidebarStyles = ReactDOMRe.Style.make(
     ~width= "56px",
     ~display = "flex"
     ()
 );

...
<RsuiteUi.Container className='...'>
    <RsuiteUi.Sidebar styles=sidebarStyles>
```
