### ISSUE TITLE
Generated import statement for RsuiteUi.RsuiteTypes.DataItemType is incorrect

### ISSUE THREAD

**Issue by benjstephenson** [shurygindv/bs-rsuite-ui-react#3]
I'm trying to use RsuiteUi.RsuiteTypes.DataItemType.make to create a data item for use with RsuiteUi.SelectPicker but get an error:
`Module not found: Error: Can't resolve 'bs-rsuite-ui-react/src/RsuiteTypes.bs.js'`

Inspecting the generated bs.js for my reasonml file the import statement is:
`import * as RsuiteTypes$RsuiteUi from "bs-rsuite-ui-react/src/RsuiteTypes.bs.js";`

Manually changing this to
`import * as RsuiteTypes$RsuiteUi from "@sdv-studio/bs-rsuite-ui-react/src/RsuiteTypes.bs.js";`
and everything works as expected, when webpack recompiles this change is lost.

**Comment by shurygindv** [comment]
@benjstephenson, This has been fixed. Feel free to close the issue, thank you!
